import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/app/components/shadcn/theme-provider";
import Nav from "./components/Nav";
import { AuroraBackground } from "./components/aurora-background";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-w-[100vw] min-h-screen overflow-x-hidden">
            <div className="flex flex-col z-50 absolute w-full px-6 py-4 min-h-screen space-y-5">
              <Nav />
              <div className=" min-h-[70vh] flex flex-col font-consolas">
                {children}
              </div>
            </div>
            <AuroraBackground>
              <div></div>
            </AuroraBackground>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
