import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/app/components/shadcn/theme-provider";
import Nav from "./components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body className={inter.className}>
          <Nav />
          <div className="container  min-h-[80vh] py-4">
            <div className="flex flex-col p-5 font-consolas dark:text-slate-400 border rounded shadow-md bg-gray-50 dark:bg-gray-950">
              {children}
            </div>
          </div>
        </body>
      </ThemeProvider>
    </html>
  );
}
